version: '3.1'
services:
  db:
    image: postgres:15.3-alpine
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: foobarhogepiyo
    volumes:
      - mb_pg_data:/var/lib/postgresql/data

  session:
    image: redis:7.0-alpine
    ports:
      - '6379:6379'
    volumes:
      - mb_redis_data:/data

volumes:
  mb_pg_data:
    external: true
  mb_redis_data:
    external: true